version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: iot_mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    ports:
      - 1884:1884
      - 9001:9001
    networks:
      network:
        ipv4_address: 172.0.0.100


  node-red:
    image: nodered/node-red:latest
    container_name: iot_node-red
    restart: always
    ports:
      - 1880:1880
    networks:
      network:
        ipv4_address: 172.0.0.102
    depends_on:
      - mosquitto

  influxdb:
    image: influxdb:latest
    environment:
            DOCKER_INFLUXDB_INIT_MODE:
            DOCKER_INFLUXDB_INIT_USERNAME: 
            DOCKER_INFLUXDB_INIT_PASSWORD: 
            DOCKER_INFLUXDB_INIT_ORG: 
            DOCKER_INFLUXDB_INIT_BUCKET: 
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 
    ports:
      - "8086:8086"
    networks:
      network:
        ipv4_address: 172.0.0.103
 
    volumes:
      - ./influxdb:/data


  openhab:
    image: "openhab/openhab:3.4.2"
    restart: always
    ports:
      - "8082:8082"
      - "8444:8444"
    volumes:
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      OPENHAB_HTTP_PORT: "8082"
      OPENHAB_HTTPS_PORT: "8444"
    networks:
      network:
        ipv4_address: 172.0.0.104
    depends_on:
      - mosquitto
  

  grafana:
    image: grafana/grafana:7.5.7
    
    ports:
      - 3003:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/Users/user/Desktop/sensor_env/influxdb_ds.yml  
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:



networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/17
